version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: configs/dockerfiles/nginx.dockerfile
    volumes:
      - "${PWD}/dist/:/etc/nginx/static:ro"
      - "${PWD}/configs/nginx/nginx.nginx:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/letsencrypt/live/meetme-app.ru/privkey.pem:/etc/letsencrypt/live/meetme-app.ru/privkey.pem:ro"
      - "/etc/letsencrypt/live/meetme-app.ru/fullchain.pem:/etc/letsencrypt/live/meetme-app.ru/fullchain.pem:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend-service-network


networks:
  frontend-service-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1